<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'profile_id' => 2,
                'brand_id' => 2,
                'category_id' => 1,
                'product_name' => 'Logitech G PRO Wireless',
                'price' => 2000.00,
                'quantity' => 29,
                'sold' => 1,
                'description' => 'Best gaming mouse!',
                'product_img' => null,
                'archived' => 0,
                'created_at' => '2025-04-04 05:11:40',
                'updated_at' => '2025-04-04 05:13:05',
            ],
            [
                'profile_id' => 2,
                'brand_id' => 1,
                'category_id' => 1,
                'product_name' => 'Razer DeathAdder V3 Pro',
                'price' => 1899.99,
                'quantity' => 35,
                'sold' => 3,
                'description' => 'Ultra-lightweight ergonomic design',
                'product_img' => null,
                'archived' => 0,
                'created_at' => '2025-04-04 06:00:00',
                'updated_at' => '2025-04-04 06:00:00',
            ],
            [
                'profile_id' => 2,
                'brand_id' => 3,
                'category_id' => 1,
                'product_name' => 'SteelSeries Aerox 3',
                'price' => 1499.50,
                'quantity' => 45,
                'sold' => 2,
                'description' => 'Super light with RGB lighting',
                'product_img' => null,
                'archived' => 0,
                'created_at' => '2025-04-04 06:15:00',
                'updated_at' => '2025-04-04 06:15:00',
            ],
            [
                'profile_id' => 2,
                'brand_id' => 4,
                'category_id' => 1,
                'product_name' => 'Corsair Dark Core RGB',
                'price' => 1799.00,
                'quantity' => 20,
                'sold' => 4,
                'description' => 'Customizable RGB with wireless charging',
                'product_img' => null,
                'archived' => 0,
                'created_at' => '2025-04-04 06:30:00',
                'updated_at' => '2025-04-04 06:30:00',
            ],
            [
                'profile_id' => 2,
                'brand_id' => 2,
                'category_id' => 1,
                'product_name' => 'Logitech G502 X Plus',
                'price' => 2199.99,
                'quantity' => 25,
                'sold' => 5,
                'description' => 'Advanced optical sensor technology',
                'product_img' => null,
                'archived' => 0,
                'created_at' => '2025-04-04 06:45:00',
                'updated_at' => '2025-04-04 06:45:00',
            ],
            [
                'profile_id' => 2,
                'brand_id' => 1,
                'category_id' => 1,
                'product_name' => 'Razer Basilisk V3',
                'price' => 1699.00,
                'quantity' => 30,
                'sold' => 2,
                'description' => 'Customizable scroll wheel',
                'product_img' => null,
                'archived' => 0,
                'created_at' => '2025-04-04 07:00:00',
                'updated_at' => '2025-04-04 07:00:00',
            ],
            [
                'profile_id' => 2,
                'brand_id' => 5,
                'category_id' => 1,
                'product_name' => 'HyperX Pulsefire Haste',
                'price' => 1299.99,
                'quantity' => 40,
                'sold' => 3,
                'description' => 'Honeycomb shell design',
                'product_img' => null,
                'archived' => 0,
                'created_at' => '2025-04-04 07:15:00',
                'updated_at' => '2025-04-04 07:15:00',
            ],
            [
                'profile_id' => 2,
                'brand_id' => 3,
                'category_id' => 1,
                'product_name' => 'SteelSeries Rival 5',
                'price' => 1599.00,
                'quantity' => 28,
                'sold' => 1,
                'description' => 'Perfect for all gaming genres',
                'product_img' => null,
                'archived' => 0,
                'created_at' => '2025-04-04 07:30:00',
                'updated_at' => '2025-04-04 07:30:00',
            ],
            [
                'profile_id' => 2,
                'brand_id' => 2,
                'category_id' => 1,
                'product_name' => 'Logitech G703 Lightspeed',
                'price' => 1899.50,
                'quantity' => 22,
                'sold' => 4,
                'description' => 'Wireless with HERO sensor',
                'product_img' => null,
                'archived' => 0,
                'created_at' => '2025-04-04 07:45:00',
                'updated_at' => '2025-04-04 07:45:00',
            ],
            [
                'profile_id' => 2,
                'brand_id' => 1,
                'category_id' => 1,
                'product_name' => 'Razer Viper Ultimate',
                'price' => 2299.99,
                'quantity' => 15,
                'sold' => 6,
                'description' => 'Ambidextrous design with charging dock',
                'product_img' => null,
                'archived' => 0,
                'created_at' => '2025-04-04 08:00:00',
                'updated_at' => '2025-04-04 08:00:00',
            ],
            [
                'profile_id' => 2,
                'brand_id' => 4,
                'category_id' => 1,
                'product_name' => 'Corsair Scimitar RGB Elite',
                'price' => 1799.00,
                'quantity' => 33,
                'sold' => 2,
                'description' => 'Adjustable side buttons',
                'product_img' => null,
                'archived' => 0,
                'created_at' => '2025-04-04 08:15:00',
                'updated_at' => '2025-04-04 08:15:00',
            ],
            [
                'profile_id' => 2,
                'brand_id' => 5,
                'category_id' => 1,
                'product_name' => 'HyperX Pulsefire Dart',
                'price' => 1499.99,
                'quantity' => 27,
                'sold' => 3,
                'description' => 'Wireless with premium switches',
                'product_img' => null,
                'archived' => 0,
                'created_at' => '2025-04-04 08:30:00',
                'updated_at' => '2025-04-04 08:30:00',
            ],
            [
                'profile_id' => 2,
                'brand_id' => 2,
                'category_id' => 1,
                'product_name' => 'Logitech G305 Lightspeed',
                'price' => 1399.00,
                'quantity' => 50,
                'sold' => 8,
                'description' => 'Affordable wireless performance',
                'product_img' => null,
                'archived' => 0,
                'created_at' => '2025-04-04 08:45:00',
                'updated_at' => '2025-04-04 08:45:00',
            ],
            [
                'profile_id' => 2,
                'brand_id' => 1,
                'category_id' => 1,
                'product_name' => 'Razer Orochi V2',
                'price' => 1699.50,
                'quantity' => 38,
                'sold' => 2,
                'description' => 'Compact wireless gaming mouse',
                'product_img' => null,
                'archived' => 0,
                'created_at' => '2025-04-04 09:00:00',
                'updated_at' => '2025-04-04 09:00:00',
            ],
            [
                'profile_id' => 2,
                'brand_id' => 3,
                'category_id' => 1,
                'product_name' => 'SteelSeries Prime Wireless',
                'price' => 1999.99,
                'quantity' => 18,
                'sold' => 5,
                'description' => 'Pro-grade precision',
                'product_img' => null,
                'archived' => 0,
                'created_at' => '2025-04-04 09:15:00',
                'updated_at' => '2025-04-04 09:15:00',
            ],
        ]);
    }
}